<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Oxygen</title>
        <link rel="stylesheet" href="http://cdn.webix.com/edge/webix.css" type="text/css"> 
        <script src="http://cdn.webix.com/edge/webix.js" type="text/javascript"></script>
    </head>
    <body>
        <?php echo $this->content; ?>    
        <?php echo $this->inlineScript() ?>
    </body>
</html>
